# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
# image: busybox:latest

before_script:
  - echo "Starting Runner"

after_script:
  - echo "Finished"

build1:
  stage: build
  script:
    - echo "Starting Build"
    - ~/Qt/5.12.3/gcc_64/bin/qmake
    - make

test1:
  stage: test
  script:
    - echo "No tests to run at this time... Please add some."